# Generated by Django 4.0.3 on 2022-03-16 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.AddField(
            model_name='tournament',
            name='completeness',
            field=models.BooleanField(default=False, verbose_name='Completeness of tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 15, 5, 23, 959602, tzinfo=utc), verbose_name='Date of start'),
        ),
    ]
