# Generated by Django 4.0.3 on 2022-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_options_remove_tournament_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='Date of start'),
        ),
    ]
